### ISSUE TITLE
Add a `Process.toUtf8` and `Process.toUtf8_`

### ISSUE THREAD

**Issue by adithyaov** [composewell/streamly-process#38]
Or we can decide on a better API.

- `Process.toUtf8`: Run the command and return all the lines
- `Process.toUtf8_`: Run the command and return the last line only

**Comment by harendra-kumar** [comment]
If it is lines then it should be `toLines`. If we want chars then it could be `toChars`. These are easily representable by idioms. We should keep the APIs experimental to begin with. I am not sure if we should have these as we can just plug a `Unicode.lines` function in the stream to achieve this. If this is common in shell programming we can possibly have a convenience function in `streamly-shell`.

For last line we can just use `Stream.last` or we can have something like `Stream.takeLast` as well to n elements from end.

**Comment by harendra-kumar** [comment]
We have `toLines` now.
